# gen-sbatch.sh - sbatch script generation for run-slurm.sh
#
# Sourced by run-slurm.sh; not meant to be run on its own.  Provides
# write_sbatch(), which emits one ready-to-submit sbatch script per correlation
# mode.  Modelled directly on the hand-written runparallel.benchsimreal /
# runparallel.benchsimrealgpu cluster scripts: source a DiFX setup script, set
# the difxmessage multicast groups to this node, start a difxlog collector in
# the background, then srun mpifxcorr.
#
# The three modes differ only in which setup script is sourced, the SLURM
# resource sizing, and whether "--usegpu" is appended, so a single template
# with a mode switch avoids duplicating near-identical files.
#
# Expects the config variables from slurm.conf to already be in the environment.

# ---------------------------------------------------------------------------
# Nsight Systems profiling toggle.
#
# Set USE_NSYS=1 (here or in the environment) to wrap the GPU correlator in an
# Nsight Systems profile.  Only the Core rank (the last MPI rank, which is the
# one that runs GPUCore/GPUMode) is profiled; every other rank runs mpifxcorr
# bare, so the trace stays small.  Reports are written to <jobdir>/nsys/ -
# derived from each job's own directory, with no absolute paths baked into the
# generated wrapper.  Only affects the gpu mode (cpu/reference runs are never
# wrapped).  Requires `nsys` to be on PATH inside the job (via the sourced setup
# script or a `module load nsight-systems`).
USE_NSYS="${USE_NSYS:-0}"
# Flags passed to `nsys profile`.  Override in the environment to taste, e.g.
# add --sample=cpu for host-thread hotspots, --cuda-memory-usage=true for a VRAM
# footprint track, or --duration=<sec> to cap the capture.
NSYS_ARGS="${NSYS_ARGS:---trace=cuda,nvtx,osrt}"
# ---------------------------------------------------------------------------

# write_sbatch <mode:cpu|gpu|reference> <expname> <jobdir>
#
# Writes <jobdir>/slurm-<mode>.sh.  The generated script cd's into <jobdir> and
# correlates <expname>.input, which run-slurm.sh has already produced there.
write_sbatch() {
    local mode="$1"
    local expname="$2"
    local jobdir="$3"

    local ntasks time mem setup gres="" usegpu=""
    case "$mode" in
        cpu)
            ntasks="$CPU_NTASKS"; time="$CPU_TIME"; mem="$CPU_MEM_PER_CPU"
            setup="$SETUP_SCRIPT"
            ;;
        gpu)
            ntasks="$GPU_NTASKS"; time="$GPU_TIME"; mem="$GPU_MEM_PER_CPU"
            setup="$SETUP_SCRIPT"
            gres="$GPU_GRES"; usegpu="--usegpu"
            ;;
        reference)
            ntasks="$REFERENCE_NTASKS"; time="$REFERENCE_TIME"; mem="$REFERENCE_MEM_PER_CPU"
            setup="$REFERENCE_SETUP_SCRIPT"
            ;;
        *)
            echo "write_sbatch: unknown mode '$mode'" >&2
            return 1
            ;;
    esac

    local script="$jobdir/slurm-$mode.sh"

    # The correlator invocation, shared by the plain and profiled paths.
    local runcmd="mpifxcorr ${expname}.input --nocommandthread ${usegpu}"

    # By default srun launches the correlator directly.  When profiling is
    # requested for a GPU run, generate a per-rank wrapper that runs nsys only
    # on the Core rank and srun that instead.
    local sruncmd="srun -n${ntasks} ${runcmd}"
    if [ "$USE_NSYS" != "0" ] && [ "$mode" = "gpu" ]; then
        local wrapper="$jobdir/nsys-wrap.sh"
        {
            echo "#!/bin/bash"
            echo "#"
            echo "# Auto-generated by gen-sbatch.sh (USE_NSYS).  Wraps mpifxcorr so that"
            echo "# ONLY the Core rank (the last MPI rank) is profiled with Nsight Systems;"
            echo "# every other rank runs mpifxcorr directly.  srun runs this with cwd set"
            echo "# to the job directory (the sbatch script cd's there first), so the nsys"
            echo "# report is written to ./nsys/ - no absolute paths are baked in here."
            echo "mkdir -p nsys"
            echo "if [ \"\$SLURM_PROCID\" = \"\$(( SLURM_NTASKS - 1 ))\" ]; then"
            echo "    exec nsys profile ${NSYS_ARGS} \\"
            echo "        --output=\"nsys/core_rank\${SLURM_PROCID}_job\${SLURM_JOB_ID}\" \\"
            echo "        --force-overwrite=true \\"
            echo "        ${runcmd}"
            echo "else"
            echo "    exec ${runcmd}"
            echo "fi"
        } > "$wrapper"
        chmod +x "$wrapper"
        sruncmd="srun -n${ntasks} ${wrapper}"
    fi

    {
        echo "#!/bin/bash"
        echo "#"
        echo "#SBATCH --job-name=difx_${expname}_${mode}"
        echo "#SBATCH --output=${jobdir}/${mode}.mpilog"
        echo "#SBATCH --ntasks=${ntasks}"
        echo "#SBATCH --time=${time}"
        echo "#SBATCH --cpus-per-task=1"
        echo "#SBATCH --mem-per-cpu=${mem}"
        echo "#SBATCH --account=${SLURM_ACCOUNT}"
        [ -n "$SLURM_PARTITION" ] && echo "#SBATCH --partition=${SLURM_PARTITION}"
        [ -n "$gres" ]           && echo "#SBATCH --gres=${gres}"
        echo ""
        echo "set -e"
        echo ""
        echo ". ${setup}"
        echo ""
        echo "# Restrict difxmessage multicast to this node so parallel jobs don't cross-talk"
        echo "export DIFX_MESSAGE_GROUP=\`hostname -i\`"
        echo "export DIFX_BINARY_GROUP=\`hostname -i\`"
        echo ""
        # Bake debug variables into the job script: sbatch environment export
        # cannot be relied on (sites configure --export=NONE), and the srun'd
        # tasks must see these.
        if [ -n "${DIFX_WEIGHT_DEBUG:-}" ]; then
            echo "export DIFX_WEIGHT_DEBUG=${DIFX_WEIGHT_DEBUG}"
            echo ""
        fi
        if [ -n "${DIFX_SPEC_DEBUG:-}" ]; then
            echo "export DIFX_SPEC_DEBUG=${DIFX_SPEC_DEBUG}"
            echo ""
        fi
        echo "cd ${jobdir}"
        echo "date"
        echo ""
        echo "# Collect the correlator log; killed once mpifxcorr returns"
        echo "difxlog ${expname} ${jobdir}/${expname}.difxlog 4 &"
        echo "difxlogpid=\$!"
        echo ""
        echo "${sruncmd}"
        echo ""
        echo "kill \$difxlogpid 2>/dev/null || true"
        echo "date"
    } > "$script"

    chmod +x "$script"
    echo "$script"
}
